### ISSUE TITLE
rollup 里不能用， rollup里还用了很多 vite 的方法，目前看只能在 vite 中

### ISSUE THREAD

**Issue by Wn-1231** [KeJunMao/unplugin-preprocessor-directives#13]
<img width="659" alt="image" src="https://github.com/user-attachments/assets/1fa95193-b392-4dfa-a946-f85454e7dde6">

src/core/context.ts 下

import { createFilter, createLogger, loadEnv } from 'vite' 

这些代码只能在 vite 有用

**Comment by KeJunMao** [comment]
可以装一个vite给这个插件当依赖用！欢迎PR搞一下不依赖vite
