### ISSUE TITLE
When using scss, files imported through @ import will not be converted

### ISSUE THREAD

**Issue by EndlessWord** [KeJunMao/unplugin-preprocessor-directives#3]
Such as:
![image](https://github.com/KeJunMao/unplugin-preprocessor-directives/assets/48582591/8a2c4f18-36bc-4926-a2c2-a9258ed7379a)
However, this can work normally:
![image](https://github.com/KeJunMao/unplugin-preprocessor-directives/assets/48582591/592b1c6c-a06b-4bae-ac60-585863f62d65)

**Comment by KeJunMao** [comment]
请问用的什么打包器呢？

**Comment by EndlessWord** [comment]
用的vite

**Comment by KeJunMao** [comment]
这是因为vite处理时，没有走到 transform 钩子，这不是这个插件的问题
